CREATE DATABASE login;
USE login;

CREATE TABLE usuarios (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL,
codigo_verificacao INT NOT NULL,
verificado BOOLEAN DEFAULT FALSE
);